### ISSUE TITLE
Config_Lite->get() without parameters does not work properly, or at least not as documented

### ISSUE THREAD

**Issue by azine** [pear/Config_Lite#11]
Hi,

first of all, thanx for that cool package to handle configuration files in php!

I found an error (either in code or documentation) in the code of Config_Lite->get() near line 390.

The docs say, that calling the get-function without parameters will return all sections. It does not, it returns $this.

The code that would return all the sections (line 413ff) cannot be reached.

I propose to remove this:
```
// lines 413ff
// all sections
if (null === $sec && array_key_exists($sec, $this->sections)) {
     return $this->sections;
}
``` 
and return `$this->sections` on line 397 instead of `$this`.

Cheers,
D.

**Comment by pce** [comment]
thanks, 
i changed `get()` and added tests in the  `issue11` branch ( https://github.com/pear/Config_Lite/tree/issue11 ), so far it seems fine.

**Comment by pce** [comment]
fixed in master
